### ISSUE TITLE
The link of dataset

### ISSUE THREAD

**Issue by maogewudi007** [harlanhong/MM2021-CO2-Net#1]
数据集不能下载，可以更新一下数据集的下载链接吗？

数据集下载错误提示如下：
![image](https://user-images.githubusercontent.com/25141812/134792000-cfac4087-866d-4883-b860-daba0337c067.png)
可能的原因：
https://answers.microsoft.com/zh-hans/msoffice/forum/all/%E4%B8%8B%E8%BD%BD%E5%88%AB%E4%BA%BA%E9%80%9A/fb0c1cd8-bf17-48e2-819a-c874dad12992

**Comment by fjchange** [comment]
We follow the dataset provided in previous works, e.g., WTAL, BaS-Net, and HAM-Net. Now we update the link as HAM-Net.
