### ISSUE TITLE
Question about function filter_segments

### ISSUE THREAD

**Issue by xyiyy** [harlanhong/MM2021-CO2-Net#2]
In the implementation, I find that function [filter_segments](https://github.com/harlanhong/MM2021-CO2-Net/blob/master/proposal_methods.py#L343) is used before evaluation. It seems some predictions are removed by using additional information from "Ambiguous_test".

**Comment by fjchange** [comment]
Without filter_segments, our CO2-Net can get performance as mAP@IoU 0.1-0.5: 52.78, mAP@0.1-0.7: 43.01, mAP@0.1~0.9: 34.36, which is still leading ahead.

**Comment by xyiyy** [comment]
> Without filter_segments, our CO2-Net can get performance as mAP@IoU 0.1-0.5: 52.78, mAP@0.1-0.7: 43.01, mAP@0.1~0.9: 34.36, which is still leading ahead.

Thanks for releasing the results!

**Comment by fjchange** [comment]
It should be known that Ambiguous_Test.txt is given by the dataset provider.  All the existing methods are compared in the same way in filtering out the ambiguous action instances in the testing set. The results we gave a month ago are not suitable to compare with other methods. Please refer to the paper for proper comparisons.
