### ISSUE TITLE
Can not reproduce the results of paper

### ISSUE THREAD

**Issue by leftthomas** [harlanhong/MM2021-CO2-Net#3]
As `readme` suggested, I used your code, data and the same hyper-parameters to train the model on `Thumos14` dataset:
<img width="780" alt="QQ20220321-142900@2x" src="https://user-images.githubusercontent.com/9991443/159214997-bb496917-a890-431b-af15-14259116aafe.png">
However I can only obtain 41.9 `mAP@AVG` for `0.1:0.7`, but the paper reported 44.6, there is about a 2.7% gap, it is a huge gap for this WSL task. Can you explain this?
<img width="790" alt="QQ20220321-142807@2x" src="https://user-images.githubusercontent.com/9991443/159215011-4a5d8c22-f3c2-458e-ab48-80a05ecb884c.png">

**Comment by fjchange** [comment]
We have re-trained the code in our environment and got similar results as the paper reported,
![image](https://user-images.githubusercontent.com/22427196/159230612-41cf5c15-1946-4b35-aec0-205dd3530b09.png),
which is consistent with the released model,
![image](https://user-images.githubusercontent.com/22427196/159231919-4a5f1b05-fc88-4a16-9d36-139041be0b3f.png)

There may cause by many reasons, we hope you can check the list below and make it better:
1. Ensure you are using the consistent hardware and software as we did. (GTX 1080 Ti + and the `environment.yaml` and the `requirement.txt`) . The learning may be influenced by the environment. Different environments may introduce different random sequence generation, which further influences the training order, leading to different results. 
![image](https://user-images.githubusercontent.com/22427196/159231546-17e24e12-50bb-466e-b4d2-9356b9a866c1.png)
2. Ensure the path of `ambiguous.Txt` in the `filter_segments` function of `proposal_methods.py` is accessible. Without filtering out the ambiguous segments, the performance may drop by over 1%. 

We hope this advice can help.
