### ISSUE TITLE
How to reproduce the results of ActivityNet1.2?

### ISSUE THREAD

**Issue by jiangerxiaozhao** [harlanhong/MM2021-CO2-Net#4]
Thanks for your release of THUMOS14. And how to reproduce the results of ActivityNet1.2? Can you provide details?

**Comment by fjchange** [comment]
The training and testing commands for ActivityNet 1.2 is available in `run.sh`.

**Comment by jiangerxiaozhao** [comment]
Sorry for ignoring it. Thank you very much!
